### ISSUE TITLE
Running the Kalman filter with missing observations

### ISSUE THREAD

**Issue by hrzn** [spmvg/nfoursid#3]
Hi @spmvg,
For Darts, we would be very interested to have a functionality where an existing Kalman filter could be used to infer missing values in a time series. This could be done for both missing-value imputation, or forecasting (if the missing values are in the future).

I have started something [here](https://github.com/unit8co/darts/pull/743), but currently I'm just replacing missing observations with the previous mean. This is likely not the best way to do it as it would yield overly confident predictions, and instead we would need to capture the fact that the measurements are really missing. We have seen that there's a method `extrapolate()` in the Kalman filter, but this one runs the state space model without input signal.

Is there an equivalent to `extrapolate()` working with input signals? Otherwise what would you recommend we do? One option I see would be to recreate the state space model on our side in order to run it one step, but that seems a bit cumbersome and I'd feel better if this stays in the realm of `nfoursid`.

Thanks!

**Comment by spmvg** [comment]
Hi! That's an interesting implementation you're working on! I like what's going on in Darts. I'll provide some comments:

First a personal opinion about missing values. In my opinion, missing values are a fact-of-life when working with real life data and should be dealt with. However, as you might have noticed, the `NFourSID` object complains when you give it `nan`s (see `_set_input_output_data`). In other words: the `NFourSID` intentionally leaves data quality issues to be handled by the user.

My reasoning behind this, is that missing values can mean several things depending on the data, such as "data not available due to technical error", "this datapoint you're requesting does not make sense", "this datapoint was an outlier", etc. Moreover, sometimes the data is such that only incidentally a datapoint is missing, and sometimes entire years of data is missing. Depending on the meaning of the missing data, there might be a different approach we should take (e.g. drop the data entirely/repeat last value/train a model/incorporate seasonality). So to fill in missing values, we have to make further assumptions, and in my opinion these assumptions should be made by the user. We can still make functions that make handling missing values easier. So I think helping the user with missing data should be the focus.

Now some comments about your message:

> missing values

Are you talking about missing values in the output or in the input of the model? I assume you mean the output, since you apparently have an input already.

> we would be very interested to have a functionality where an existing Kalman filter could be used to infer missing values in a time series
> Is there an equivalent to extrapolate() working with input signals?

Indeed what you're asking is pretty much what `Kalman.extrapolate` does, only then with inputs.

For now I think the way to solve it, is to use the same implementation as `.extrapolate`, but then to provide the inputs to `state_space.step`:

```python
from nfoursid.state_space import StateSpace
...
kalman = ...some kalman filter stepped until the missing data...

state_space = StateSpace(
    kalman.state_space.a,
    kalman.state_space.b,
    kalman.state_space.c,
    kalman.state_space.d,
    x_init=kalman.x_predicteds[-1],
    y_column_names=kalman.state_space.y_column_names,
    u_column_names=kalman.state_space.u_column_names
)

for _ in range(timesteps):
    state_space.step()  # inputs go here
```

A relatively trivial addition for me could be to support a list of inputs in the `.extrapolate` function.

Keep in mind that if you extrapolate for missing data in the middle of a dataset, you're of course not taking into account the information of where the data is going in the future (which you know already since the data is missing in the middle), so you have no guarantee of a good connection with the timesteps in the future. You don't know the noise terms that were added in reality. Depending on the purpose of the analysis, this might be an issue or not.

FYI a little background on why the extrapolate function doesn't take inputs in the current implementation: a Kalman filter can be used inside of a real-time control loop. In this implementation, the question becomes: "what inputs should I give the system to reach desired state Y?". We already know how the system responds to inputs (trivially the matrix D) but we don't know how the system will evolve autonomously. So therefore the function `.extrapolate` returns where the system is going, and then the control loop can correct to reach the desired state.

> This is likely not the best way to do it as it would yield overly confident predictions

Anytime you're filling in missing data, you're making assumptions, so I'm not sure if there is a one-size-fits-all best way that satisfies everyone...

> Otherwise what would you recommend we do?

I would leave these kind of data-quality issues to the user. I would make some general functions to fill missing data (one of them could use the Kalman filter internally, another could use for example linear interpolation). But I would not integrate handling missing data inside the forecasting methods directly. That's just my opinion though! (:

**Comment by hrzn** [comment]
Thanks a lot for your detailed answer @spmvg !

> First a personal opinion about missing values. In my opinion, missing values are a fact-of-life when working with real life data and should be dealt with. However, as you might have noticed, the NFourSID object complains when you give it nans (see _set_input_output_data). In other words: the NFourSID intentionally leaves data quality issues to be handled by the user.

> My reasoning behind this, is that missing values can mean several things depending on the data, such as "data not available due to technical error", "this datapoint you're requesting does not make sense", "this datapoint was an outlier", etc. Moreover, sometimes the data is such that only incidentally a datapoint is missing, and sometimes entire years of data is missing. Depending on the meaning of the missing data, there might be a different approach we should take (e.g. drop the data entirely/repeat last value/train a model/incorporate seasonality). So to fill in missing values, we have to make further assumptions, and in my opinion these assumptions should be made by the user. We can still make functions that make handling missing values easier. So I think helping the user with missing data should be the focus.

Concerning handling missing values, I agree with you that there might be many underlying reasons for this, and it might get almost philosophical :) However, I think very often the role of models is precisely to fill in missing values. Of course, that's always based on hypotheses -- for instance in the case of a Kalman filter, if we use it, we accept the hypothesis that the data is generated by a linear dynamical system with Gaussian noise -- but I suspect that for many users it might be extremely useful to know the values predicted by the filter in the absence of observations. In fact I believe that's the reason many people use a Kalman filter (outside of control use-cases) to begin with. Some users are using Darts *in order to solve* their data quality issues using (hopefully good) models. In the case of forecasting, it is even more obvious: future values are (more or less by definition) unknown and users of Darts use such tools precisely because they need it to fill in those "missing" values.

> Are you talking about missing values in the output or in the input of the model? I assume you mean the output, since you apparently have an input already.

I was referring to outputs, but in fact this would also be relevant for inputs. However, if we interpret "missing data in the input" as "no input" then (I believe) setting the inputs to 0 does the job. But I might be missing something here.

> Keep in mind that if you extrapolate for missing data in the middle of a dataset, you're of course not taking into account the information of where the data is going in the future (which you know already since the data is missing in the middle), so you have no guarantee of a good connection with the timesteps in the future. You don't know the noise terms that were added in reality. Depending on the purpose of the analysis, this might be an issue or not.

I think that's not an issue. We can explain in the Darts documentation that in this case missing value imputation is realised by running a Kalman Filter forward in time; and then it is up to the users to decide if that's a useful imputation method for them or not.

> Anytime you're filling in missing data, you're making assumptions, so I'm not sure if there is a one-size-fits-all best way that satisfies everyone...

In the context of the KF, using the current mean is problematic not just because it reduces the uncertainty, but because I believe it kind of violates the expectation anyone familiar with the KF would have that the output should come from the "current" state space model directly, absent of observations.

I think the code snippet you provide probably does what I need - thanks a lot! I will try this. Let me know if at some point you intend to write an `extrapolate()` method accepting inputs, which would be useful as it'd leave this part of the logic inside `nfoursid`.

**Comment by spmvg** [comment]
> it might get almost philosophical :)

It does indeed!

> Some users are using Darts in order to solve their data quality issues using (hopefully good) models.

That's a good reason then! You also indicate that you explain to users how the imputation is done, so that's good.

> However, if we interpret "missing data in the input" as "no input" then (I believe) setting the inputs to 0 does the job. But I might be missing something here.

It depends on the application. If the Darts user understands that missing inputs are interpreted as "no input", then it's fine to set the input to zero.

> Let me know if at some point you intend to write an extrapolate() method accepting inputs, which would be useful as it'd leave this part of the logic inside nfoursid.

I will let you know if I extend it.

For now it looks like you can continue so I suggest closing this issue. Let's re-open it if necessary.

**Comment by hrzn** [comment]
Thanks for the answer!
Although it is helpful to be able to run the state space model, I'm not in fact sure I can continue without a way to make the Kalman Filter make a step() without measurement. But I suspect extending step() to support this should be quite easy. Would you be open to receive a PR in this direction?

**Comment by spmvg** [comment]
In my previous comment I posted a code snipped about how to extrapolate given the state of the Kalman filter and known inputs. I feel like I misunderstand your intent, so let me know where I misunderstand. What I think is as follows:

First some general things:
* There are 3 relevant parameters in the state space model in this discussion:
  * The input
  * The internal state
  * The output
* The job of the state space model is to calculate the internal state and the output given the input
* The job of the Kalman filter is to estimate the internal state given an output and an input. For the Kalman filter to make a step, it needs an input and an output.

As far as I understand your intent, it is as follows. You have the following example dataset
```
timestamp input output
1         11    21
2         12    22
3         13    nan
4         14    nan
5         15    25
6         16    26
```

You don't know the output of steps 3 and 4, but you know the input. Given my understanding of our previous comments, you want to extrapolate using the Kalman filter to fill in the outputs for steps 3 and 4.

I thought your intended approach was as follows:
* Step the Kalman filter on steps 1 and 2 in the usual way (known input and output)
* You cannot step the Kalman filter anymore since you don't know the output, but you want to fill in the missing values using the model. Take the latest internal state of the Kalman filter and create a state space model. Extrapolate with the known inputs to obtain steps 3 and 4 (see the code snippet https://github.com/spmvg/nfoursid/issues/3#issuecomment-1024941874). The state space takes the input and calculates the output. Notice that I do not operate directly on `kalman.state_space`, but I create another state space model to do the extrapolation.
  * Since you estimated the outputs now, also step the Kalman filter on steps 3 and 4 (known input and output).
* Step the Kalman filter on steps 5 and 6 (known input and output)

Since there are other ways of handle missing values, I don't think it's nice to fill in missing values in the nfoursid implementation (then I make assumptions). But since you document the behaviour in Darts, I think it's OK to do it inside Darts.

(Also a question from me: how are you able to perform system identification (fit a model) when your data contains nans? This is the step before you can use the Kalman filter)

**Comment by hrzn** [comment]
> The state space takes the input and calculates the output. Notice that I do not operate directly on kalman.state_space, but I create another state space model to do the extrapolation.
Since you estimated the outputs now, also step the Kalman filter on steps 3 and 4 (known input and output).

Your description of my intended approach is quite accurate, but this part may cause some issues (I think). If I simply use the output of the state space model as outputs to step the KF, I suspect it might cause issues because it will trigger an update of the KF based on a fictive measurement. Rather, I was thinking we would need a way to step the KF (update its state distribution based on the state space model), but without the "update" phase where we use measurements. I'm not sure if it totally makes sense or not.

I believe this would be the natural way to step a KF without measurements, but I might be wrong (I'm not a KF expert). Either way I understand if you don't want to include such a feature in nfoursid.

> (Also a question from me: how are you able to perform system identification (fit a model) when your data contains nans? This is the step before you can use the Kalman filter)

System identification will not work on series containing NaNs. I foresee use-cases where you can use e.g. system identification on a full series to do forecasting, or you can use a KF to do missing values imputation but without relying on system identification (or using identification on a sub-slice only).

**Comment by spmvg** [comment]
> I suspect it might cause issues because it will trigger an update of the KF based on a fictive measurement

What kind of issues do you suspect? It's not perfect, but since there is missing data, there will be a trade-off anyway I think...

I cannot think of an approach of handling the missing data that will please everyone (and without delving into the "philosophy of the meaning of the nans" haha). For example, the best approach will probably differ if you have 1 or 100.000 missing datapoints. 

> I was thinking we would need a way to step the KF (update its state distribution based on the state space model), but without the "update" phase where we use measurements. I'm not sure if it totally makes sense or not.

nfoursid.kalman needs to have outputs (measurements): the internal state cannot be updated if the output is nan. Another approach can of course be to simply skip the steps with missing data: keeping the last internal state and ignoring the missing inputs and outputs, and then continuing stepping the Kalman filter afterwards. The Kalman filter will eventually converge again to an internal state. Also not perfect of course: tradeoffs...

> I foresee use-cases where you can use e.g. system identification on a full series to do forecasting, or you can use a KF to do missing values imputation but without relying on system identification (or using identification on a sub-slice only).

This makes sense. Then you will train the model without nans, and use it to fill in missing data.

**Comment by hrzn** [comment]
> What kind of issues do you suspect? It's not perfect, but since there is missing data, there will be a trade-off anyway I think...

Actually I'm not sure about that. I think there is only one "natural" way to use a Kalman filter for inferring missing data, and it simply consists in running steps of the underlying state space model.

> I cannot think of an approach of handling the missing data that will please everyone (and without delving into the "philosophy of the meaning of the nans" haha). For example, the best approach will probably differ if you have 1 or 100.000 missing datapoints.

There are many approaches for filling missing data, but I believe only one "natural" approach which uses a Kalman filter.

> nfoursid.kalman needs to have outputs (measurements): the internal state cannot be updated if the output is nan. Another approach can of course be to simply skip the steps with missing data: keeping the last internal state and ignoring the missing inputs and outputs, and then continuing stepping the Kalman filter afterwards. The Kalman filter will eventually converge again to an internal state. Also not perfect of course: tradeoffs...

I think skipping steps would not be "correct", because it would miss the state updates which could be performed with the state space model anyway, also in the absence of observations. Instead, I think that if we wanted to go there, one option could be in `step()` to just run one step of the state space model, but skip the "kalman gain terms" (if I can call them like that), which serve to take the output into accounts, if there is no output.

Now, I understand that you don't want to change the signature of `step()`, and so I won't push much further :) However, maybe before we close this, I wanted to outline a bit differently why I thought that might be a good idea both for nfoursid and for Darts. 

Imagine a user, let's call him Bob. Bob has some data, but he has a problem because his data has missing values. We don't know why - it could be sensor faults, data loss, scratches on the hard drive made by his cat, or maybe Bob's teacher has intentionally removed some data points because it's in the context of a dynamical systems exam - we don't know. However, Bob knows that the process generating the data is probably well represented by a noisy linear dynamical system. So he thinks: "Great! I'll use a Kalman filter, and if I get the parameters right I can use it to fill my missing values, with appropriate distributions!". Note that Bob makes the choice of using a Kalman filter to fill in his missing values, because he knows from his domain knowledge that's appropriate (the library did not make this choice for him). Now Bob finds nfoursid and thinks this is great! It can even be used to do system identification on the parts of his data that don't have holes, so he doesn't even have to bother about that. Now he needs to run the Kalman filter on his data. `step()` also works when `y` is `None`, and in this case, simply does a step of the system, updating the state but without the term depending on measurements. Now, Bob can even us his KF to do forecasting using Darts, to predict future values by stepping the KF a few steps in the future, and quickly compare this to other forecasting models. Everyone is happy :)

**Comment by hrzn** [comment]
Just fyi: This is what the `step()` function accepting missing values would look like according to my reasoning above :)
https://github.com/unit8co/darts/blob/ba5955e6d0f1cebc00aa8a74088042125b0aae54/darts/models/filtering/kalman_filter.py#L21

**Comment by tomasvanpottelbergh** [comment]
> Just fyi: This is what the `step()` function accepting missing values would look like according to my reasoning above :) https://github.com/unit8co/darts/blob/ba5955e6d0f1cebc00aa8a74088042125b0aae54/darts/models/filtering/kalman_filter.py#L21

I think this implementation makes sense. It also seems to be consistent with other Kalman filter implementations, where the Kalman gains are set to zero when the observation is missing (see [pykalman](https://pykalman.github.io/#missing-measurements) which handles missing values).

I think it would be great to have something like this in nfoursid. If you are afraid that this will make the behaviour related to missing values too opaque, would it be an option to add an argument to the step function to enable this?

**Comment by spmvg** [comment]
First, let me say that I really appreciate the clarity and effort that you put into the explanations.
I must correct myself: I think you really have a point about the functional need for handling missing outputs in the Kalman stepping.

One thing that I realized just now, is that are talking about the same thing: we are just calculating it differently.
If the output given to the Kalman filter is the same as what it expects (by stepping the state space model), then the term `y - self.state_space.d @ u - self.state_space.c @ x_pred` will be zero.
So then my [suggestion](https://github.com/spmvg/nfoursid/issues/3#issuecomment-1026865025) and your [suggestion](https://github.com/unit8co/darts/blob/ba5955e6d0f1cebc00aa8a74088042125b0aae54/darts/models/filtering/kalman_filter.py) produce the same result.
One sidenote is that you are [not updating](https://github.com/unit8co/darts/blob/ba5955e6d0f1cebc00aa8a74088042125b0aae54/darts/models/filtering/kalman_filter.py#L77) `p_filtereds`, but this is still necessary since it is iteratively solving an equation.

So we're not talking about _what_ to do, but _how_ to do it. I'm convinced that there is a need to be able to provide no output, and the nicest way is indeed to edit the Kalman stepping.

I looked at your code and adjusted it a bit: https://github.com/spmvg/nfoursid/pull/7. Does this work for your purpose?

I would like to ask the following:
* Could you run existing Darts tests against this branch of nfoursid: https://github.com/spmvg/nfoursid/pull/7
* Could you check if the branch works for the new Darts feature?

If this is all OK, I will create a new release with an increased major revision number since there is a change in how data is handled in an existing API.

**Comment by hrzn** [comment]
Hi @spmvg, many thanks for the changes brought to the `step()` function! It looks perfect. I've tested with Darts, and it works very well out of the box 👍 
Let me know once you make a new release, and I'll update our dependency version on nfoursid before we release the new feature.

(Here's what it looks like when used for forecasting):
![image](https://user-images.githubusercontent.com/4806678/152333512-663098d4-6cf3-4541-9e6a-3506a51adf58.png)

**Comment by spmvg** [comment]
Thanks a lot for your cooperation! It looks really nice, and I'm happy with it!

The version is upgraded to 1.0.0 on both PyPi and Conda-Forge. I think we can close this issue!
