### ISSUE TITLE
subspace_identification fails with error: numpy.core._exceptions._ArrayMemoryError

### ISSUE THREAD

**Issue by davidusb-geek** [spmvg/nfoursid#9]
Hi.
I am trying to do a simple SS system identification with just one input one output data.

My DF looks like this:
```
        in_GCU_SetPoint  out_Power_Generated
0         400000.000000        400000.000000
1         400000.000000        400000.000000
2         400736.555429        400000.000000
3         400754.602332        400000.118062
4         400775.720210        400000.470194
...                 ...                  ...
399996    178240.715021        179116.368182
399997    178241.535780        179103.388731
399998    178242.510933        179090.539037
399999    178243.640503        179077.819439
400000    178244.924511        179065.230272

[400001 rows x 2 columns]
```

And my code snippet is:
```
data_df = pd.DataFrame(np.hstack((u,y)), columns=['in_GCU_SetPoint', 'out_Power_Generated'])
nfoursid = NFourSID(
data_df,  # the state-space model can summarize inputs and outputs as a dataframe
output_columns=['out_Power_Generated'],
input_columns=['in_GCU_SetPoint'],
num_block_rows=10
)
nfoursid.subspace_identification()
ORDER_OF_MODEL_TO_FIT = 4
state_space_identified, covariance_matrix = nfoursid.system_identification(rank=ORDER_OF_MODEL_TO_FIT)
```

But this fails with the following error:
```
Traceback (most recent call last):
  File ".venv\lib\site-packages\numpy\linalg\linalg.py", line 1642, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.16 TiB for an array with shape (399992, 399992) and data type float64
```

Any idea of what I am doing wrong?

**Comment by spmvg** [comment]
Hi @davidusb-geek! Thanks for your response. I see that you run into an out of memory issue. In order to identify the model, NFourSID needs to work with some matrices that scale O(n^2) in the number of datapoints. There of course needs to be memory available to work with those matrices. Also, depending on the order of your system, you might be able to use fewer datapoints than you are currently using. I think you have the following options:

* Use an instance with more memory
* Limit the number of datapoints used (for example: use only the most recent ones, or subsample the dataset)

I'm closing this issue since I think this is not an issue with NFourSID, and you're also not doing anything wrong as far as I see, you're just running out of memory! :)

**Comment by davidusb-geek** [comment]
Ok thank you. I will reduce the number of data points.
When doing this in Matlab it works in same machine and the same number of data points. I guess that in their code their are reducing the dataset under the hood.
